name: Build/release

on:
  push:
    branches:
      - release

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Fetch full history
        run: git fetch --unshallow --recurse-submodules=no

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Run compile
        uses: borales/actions-yarn@v4
        with:
          cmd: compile:prod

      - name: Run changelog
        uses: borales/actions-yarn@v4
        with:
          cmd: changelog

      - name: Build/release Electron app
        uses: borales/actions-yarn@v4
        with:
          cmd: dist

      - name: Publish release
        uses: borales/actions-yarn@v4
        with:
          cmd: gh-release
